version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'uat'
    commit-message: 'chore(deps): update all dependencies'
    single-branch: true
    allow:
      - dependency-type: 'all'
