export const components = [
	{ name: 'Accordion' },
	{ name: 'Avatar' },
	{ name: 'Banner' },
	{ name: 'Breadcrumbs' },
	{ name: 'Button' },
	{ name: 'Card' },
	{ name: 'Carousel' },
	{ name: 'Chip' },
	{ name: 'Cookie Consent', href: '/components/CookieConsent' },
	{ name: 'Drawer' },
	{ name: 'Footer' },
	{ name: 'Jumbotron' },
	{ name: 'Loader' },
	{ name: 'Nav Bar', href: '/components/NavBar' },
	{ name: 'Popover' },
	{ name: 'Sidebar' },
	{ name: 'Sortable' },
	{ name: 'Stepper' },
	{ name: 'Switch' },
	{ name: 'Table' },
	{ name: 'Text Area', href: '/components/TextArea' },
	{ name: 'Text Input', href: '/components/TextInput' },
	{ name: 'Toaster' },
	{ name: 'Video Player', href: '/components/VideoPlayer' },
];
