name: CI UAT Merged

on:
  push:
    branches:
      - uat

env:
  NODE_VERSION: 20.x

jobs:
  test:
    name: Vitest & Playwright
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }} 🛒
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Node Packages 🛒
        run: npm i

      - name: Lint 🧽
        run: npm run lint

      - name: Run Vi tests 🏃
        run: npm run test:unit

      - name: Install playwright browsers 🛒
        run: npx playwright install --with-deps

      - name: Run Playwrite tests 🏃
        run: npm run test

  zap:
    name: ZAP Baseline Scan
    runs-on: ubuntu-latest
    concurrency:
      group: zap-uat
      cancel-in-progress: true
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }} 🛒
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Node Packages 🛒
        run: npm i

      - name: Build app 🧱
        run: npm run build

      - name: Launch app 🚀
        run: npm run preview &

      - name: Wait for app to start ☕️
        run: sleep 10

      - name: Run ZAP Automation Framework
        uses: StafflinePeoplePlus/zap-automation-framework@1.0.0
        with:
          config-dir: 'zap-config'
          autorun-file: 'baseline.yaml'
          create-issue: true
          fail-action-on-warning: true
          issue-title: 'ZAP Report - ${{ github.head_ref || github.ref_name }}'

  a11y:
    name: Accessibility Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v3

      - name: Use Node.js 18 🛒
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Node Packages 🛒
        run: npm i

      - name: Build app 🧱
        run: npm run build

      - name: Launch app 🚀
        run: npm run preview &

      - name: Wait for app to start ☕️
        run: sleep 10

      - name: Accessibility scan 🩻
        uses: a11ywatch/github-actions@v1.14.1
        with:
          WEBSITE_URL: ${{ vars.UAT_URL }}
          SUBDOMAINS: false
          LIST: true
          TLD: false
          SITE_WIDE: true
          UPGRADE: true
